apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:           # ‚Üê stringData is nicer because you can use plain text
  DB_NAME: budget_db
  DB_USER: postgres
  DB_PASSWORD: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://budget-db-service:5432/budget_db